name: platform_calendar
description: Platform calendar info.
version: 0.0.1
homepage: https://github.com/MagTuxGit/flutter_platform_calendar

environment:
  sdk: '>=3.1.3 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      android:
        package: app.xtiles.platform_calendar
        pluginClass: PlatformCalendarPlugin
      ios:
        pluginClass: PlatformCalendarPlugin
